site_name: My Sewing Inventory
theme:
  name: material
  features:
    - navigation.path
    - navigation.tracking
    - content.tabs.link
    - toc.integrate

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: stylesheets.extra.css
      accent: stylesheets.extra.css
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: stylesheets.extra.css
      accent: stylesheets.extra.css
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          - https://mkdocstrings.github.io/autorefs/objects.inv
          - https://www.mkdocs.org/objects.inv
          - https://python-markdown.github.io/objects.inv
          paths: [src]
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: true
            # docstring_section_style: list
            filters: ["!^_"]
            # heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home: index.md
  - Patterns: patterns.md